### PR TITLE
AIW-3725 - Restructure Automate docs

### PR DESCRIPTION
**Pull request by aMacDawg**
AIW-3725 - Restructure Automate tutorials/blog docs

### CODE REVIEW

**Comment by aMacDawg** [comment]
fyi: restructuring the 4 existing blogs as tutorials, and publishing the 5th blog post

**Review by kfiry — CHANGES_REQUESTED** [review]
1. The "Tutorials" title is strange... It's in [], and not clickable. 
2. The tutorial pages are all 404

**Comment by aMacDawg** [comment]
thanks @kfiry , my latest update seems to have fixed the dead link and the 404s. Resolving the broken image path next

**Review by kfiry — CHANGES_REQUESTED** [review]
There's still an issue with the Tutorials page. Is it the same url as the first blog/tutorial, instead of it's own page with TOC of the tutorials or something along those ines

**Comment by aMacDawg** [comment]
Confirming an update to the sidebar with a dedicated Automate Studio tutorials home page

**Review by Aaron-Daniel — APPROVED** [review]

**Pull request closed without merging**
